"use client";

import { useLocale } from "next-intl";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

function LegalEs() {
    return (
        <div className="legal-container">
            <style dangerouslySetInnerHTML={{
                __html: `
        .legal-container {
          color: #1a1a1a;
          line-height: 1.6;
          font-family: sans-serif;
        }
        .legal-container h1 { font-size: 2.5rem; font-weight: 800; margin-bottom: 2rem; border-bottom: 2px solid #eee; padding-bottom: 1rem; }
        .legal-container h2 { font-size: 1.5rem; font-weight: 700; margin-top: 2.5rem; margin-bottom: 1rem; color: #3048ab; }
        .legal-container h3 { font-size: 1.1rem; font-weight: 700; margin-top: 1.5rem; }
        .legal-container p { margin-bottom: 1.2rem; text-align: justify; }
        .legal-container ul { margin-bottom: 1.2rem; padding-left: 1.5rem; list-style-type: disc; }
        .legal-container li { margin-bottom: 0.5rem; }
        .legal-container section { margin-bottom: 3rem; }
      `}} />

            <section>
                <h1 id="t-rminos-y-condiciones">Términos y Condiciones</h1>
                <p>Estos términos regulan la relación entre START WORKS MARKETING S.A. DE C.V. “Wonder Mx” y cualquier persona que use el sitio wondermx.com, consulte nuestros servicios o reserve una experiencia. Están organizados como un glosario: cada entrada define un término que aparece en la relación entre el viajero y Wonder Mx, y dentro de esa definición viven las condiciones que aplican. El uso del sitio implica la aceptación de la totalidad de lo aquí descrito, conforme a los artículos 1792 y 1803 del Código Civil Federal.  </p>
                <ol>
                    <li><strong>Identificación.</strong> START WORKS MARKETING S.A. DE C.V., RFC: SWM230217SE3, domicilio: AVENIDA TAMAULIPAS 150, PISO 18 INT 1801, COLONIA HIPODROMO, COLONIA HIPODROMO, DELEGACIÓN CUAUHTEMOC, C.P. 06100 CIUDAD DE MEXICO correo: <a href="mailto:contacto@ournextrip.com.mx" title="mailto:contacto@ournextrip.com.mx">contacto@wondermx.com</a>, sitio: wondermx.com. Ante cualquier duda puede contactarnos a través del formulario del sitio.  </li>
                    <li><strong>Experiencia.  </strong>Cualquier servicio turístico ofrecido por Wonder Mx, ya sea una actividad del catálogo publicado en el sitio o un itinerario diseñado a medida. Incluye, de forma enunciativa: tours gastronómicos, culturales y de aventura, traslados, reservas en restaurantes, actividades de bienestar, accesos a sitios con prioridad VIP y combinaciones de los anteriores. Cada experiencia del catálogo describe sus inclusiones, exclusiones y condiciones particulares en su página de producto.  </li>
                    <li><strong>Cotización personalizada.  </strong>Propuesta de itinerario elaborada por el concierge a medida del viajero, basada en la información que este proporcionó sobre sus fechas, intereses, número de personas y presupuesto. La cotización no genera ninguna obligación de pago hasta que el viajero la aprueba expresamente. El pago de una cotización personalizada se procesa a través del apartado de Experiencia Personalizada en el sitio, ingresando el folio o nombre de paquete acordado con el concierge.  </li>
                    <li><strong>Concierge</strong> <strong>.  </strong>La persona asignada por Wonder Mx para diseñar, coordinar y acompañar la experiencia del viajero. El concierge es el punto de contacto directo durante el viaje, disponible por chat o llamada para atender cambios, dudas o situaciones imprevistas en tiempo real. Su rol es el de intermediario activo entre el viajero y los proveedores, no el de ejecutor directo de los servicios en destino.  </li>
                    <li><strong>Uso permitido.</strong> El sitio wondermx.com está disponible exclusivamente para personas con capacidad legal para contratar que lo usen con fines lícitos relacionados con la consulta y contratación de experiencias turísticas. Queda prohibido: usar el sitio para actividades ilegales o fraudulentas; copiar, reproducir o distribuir el contenido, las imágenes, los textos o el diseño del sitio sin autorización escrita de START WORKS MARKETING S.A. DE C.V.; usar de forma no autorizada la marca Wonder Mx, su logotipo o cualquier elemento de propiedad intelectual; e introducir código malicioso o intentar acceder sin autorización a sistemas o bases de datos del sitio.  </li>
                    <li><strong>Uso del sitio.  </strong>El acceso a wondermx.com y el envío del formulario de contacto implican la aceptación de estos términos y de la Política de Privacidad de Wonder Mx. El sitio está disponible para personas con capacidad legal para contratar. Wonder Mx se reserva el derecho de rechazar cualquier solicitud sin necesidad de expresar causa. Las controversias que deriven del uso del sitio o de los servicios se someten a la jurisdicción de los tribunales competentes de la Ciudad de México, renunciando a cualquier otro fuero.  </li>
                    <li><strong>Precios.</strong> Todos los precios publicados en wondermx.com se muestran en moneda nacional, pesos mexicanos (MXN), e incluyen el Impuesto al Valor Agregado (IVA) salvo que se indique expresamente lo contrario en una cotización o producto específico. Los precios pueden variar por temporada, disponibilidad y políticas de los proveedores; sin embargo, una vez que el viajero completa el pago y recibe su confirmación, Wonder Mx respetará el precio pactado, salvo en casos de errores evidentes de captura (por ejemplo, montos notoriamente desproporcionados o incoherentes), en cuyo caso se informará al viajero y se le ofrecerá la opción de mantener la experiencia al precio correcto o cancelar con reembolso íntegro.  </li>
                    <li><strong>Métodos de pago.</strong> Wonder Mx acepta pagos mediante tarjetas de crédito y débito emitidas por instituciones financieras autorizadas, así como otros medios electrónicos que se indiquen en wondermx.com (por ejemplo, pasarelas de pago certificadas u otras formas de pago digital). La disponibilidad de métodos de pago puede variar según el país de emisión de la tarjeta, el banco o las condiciones de la pasarela. Al realizar el pago, el viajero declara ser titular del medio de pago utilizado o contar con autorización para emplearlo.  </li>
                    <li><strong>IVA.  </strong>Todos los precios publicados en el catálogo de wondermx.com incluyen el Impuesto al Valor Agregado al 16%, conforme a la Ley del IVA vigente. Los precios de cotizaciones personalizadas incluirán IVA y se especificarán en la propuesta enviada por el concierge. START WORKS MARKETING S.A. DE C.V. emitirá el comprobante fiscal digital correspondiente a cada operación.  </li>
                    <li><strong>Pago.  </strong>El sitio procesa pagos a través de una pasarela encriptada. Wonder Mx no almacena ni tiene acceso a los datos completos de tarjetas bancarias; ese manejo ocurre íntegramente dentro del entorno del procesador certificado. La confirmación del pago activa la gestión de la reserva. El incumplimiento de un pago acordado en una cotización personalizada deja sin efecto los compromisos de reserva adquiridos por Wonder Mx con proveedores.  </li>
                    <li><strong>Antelación mínima.  </strong>Wonder Mx solicita que las reservas se realicen con al menos 34 días naturales de anticipación a la fecha de inicio de la experiencia. Este plazo es necesario para garantizar disponibilidad con los proveedores. Solicitudes con menos tiempo se atienden sujeto a lo que sea posible conseguir en ese momento, y Wonder Mx será explícito sobre qué puede y qué no puede garantizar dentro de ese plazo reducido.  </li>
                    <li><strong>Preferencias especiales.  </strong>Información que el viajero puede compartir al momento de contactar o contratar: alergias alimentarias, requerimientos de accesibilidad, restricciones dietéticas, niveles de actividad física u otras condiciones relevantes para el diseño de la experiencia. Wonder Mx utiliza esta información para tomar decisiones concretas con los proveedores. La precisión de esta información es responsabilidad del viajero; Wonder Mx no puede garantizar adaptaciones basadas en datos incompletos o no comunicados.  </li>
                    <li><strong>Confirmación.</strong> Al completar el pago de una experiencia del catálogo o de una cotización personalizada, Wonder Mx enviará al correo registrado una confirmación electrónica con el detalle de la operación: nombre de la experiencia, fecha, monto pagado y folio de reserva. Esta confirmación constituye el comprobante de la transacción y es necesaria para cualquier gestión posterior.  </li>
                    <li><strong>Revocación.</strong> Conforme al artículo 56 de la Ley Federal de Protección al Consumidor, en compras realizadas a través de medios electrónicos el consumidor tiene derecho a revocar su consentimiento dentro de los cinco días hábiles siguientes a la fecha de la transacción, siempre que la experiencia no haya sido ejecutada ni iniciada. Para ejercer este derecho, el cliente debe notificarlo por escrito a <a href="mailto:contacto@ournextrip.com.mx" title="mailto:contacto@ournextrip.com.mx">contacto@wondermx.com</a> dentro del plazo señalado.  </li>
                    <li><strong>Suspensión.</strong> Wonder Mx se reserva el derecho de suspender o cancelar el acceso al sitio y cualquier reserva en curso cuando se detecte: uso fraudulento del sitio o de métodos de pago; incumplimiento de estos términos; uso del servicio con fines ilegales o que causen daño a terceros; o cualquier conducta que Wonder Mx considere incompatible con la naturaleza del servicio. En estos casos no procede reembolso si el incumplimiento es atribuible al cliente.  </li>
                    <li><strong>Cancelación.  </strong>El acto de dejar sin efecto una reserva confirmada. Las condiciones económicas que aplican según el momento en que ocurra la cancelación están descritas de forma completa en la Política de Reembolsos de Wonder Mx, que forma parte integral de estos términos.  </li>
                    <li><strong>Proveedor.  </strong>Tercero independiente que ejecuta directamente los servicios que componen una experiencia: restaurantes, operadores de tours, empresas de transporte, guías, recintos culturales u otros. Wonder Mx actúa como coordinador y concierge, no como ejecutor directo. Selecciona a sus proveedores con criterio, pero no controla factores externos como decisiones operativas de terceros, capacidad, horarios o condiciones en destino. Ante cambios por parte de un proveedor, Wonder Mx notificará al viajero y buscará una alternativa equivalente.  </li>
                    <li><strong>Responsabilidad de </strong> <strong>Wonder Mx</strong> <strong>.</strong> Wonder Mx actúa como diseñador, coordinador y concierge de experiencias, y en muchos casos como intermediario entre el viajero y los proveedores que ejecutan directamente los servicios en destino. La responsabilidad por la operación material del servicio (horarios, ejecución del tour, condiciones del establecimiento, entre otros) corresponde al proveedor, conforme a sus propias políticas. En la medida permitida por la legislación aplicable, Wonder Mx no será responsable por daños indirectos, lucro cesante o pérdida de oportunidades derivados del uso del sitio o de los servicios contratados. En caso de que se determine una responsabilidad directa de Wonder Mx frente al viajero, ésta se limitará, como máximo, al monto efectivamente pagado por la experiencia específica de que se trate, sin perjuicio de los derechos irrenunciables que la Ley Federal de Protección al Consumidor otorga al consumidor.  </li>
                    <li><strong>Propiedad intelectual.</strong> El contenido del sitio wondermx.com, incluyendo textos, imágenes, diseño, logotipos, nombre comercial Wonder Mx y software, es propiedad de START WORKS MARKETING S.A. DE C.V. o de sus licenciantes y está protegido por las leyes mexicanas de propiedad intelectual. Ningún elemento puede ser reproducido, distribuido o utilizado sin autorización expresa y por escrito de START WORKS MARKETING S.A. DE C.V.  </li>
                    <li><strong>Fuerza mayor.  </strong>Eventos fuera del control de Wonder Mx que impidan la realización de una experiencia: condiciones climáticas extremas, cierre de sitios por autoridad competente, situaciones de seguridad en el destino u otros eventos imprevisibles e irresistibles. En estos casos Wonder Mx ofrecerá en primera instancia la reprogramación. Si no es posible o el viajero no la acepta, se tramitará el reembolso del monto pagado menos los costos irrecuperables ya comprometidos con proveedores, con detalle por escrito.  </li>
                    <li><strong>Disposiciones finales.</strong> Estos términos y condiciones constituyen el acuerdo íntegro entre START WORKS MARKETING S.A. DE C.V. “Wonder Mx” y el viajero en relación con el uso de wondermx.com y la contratación de experiencias a través del sitio, sustituyendo cualquier entendimiento o acuerdo previo, verbal o escrito, sobre las mismas materias. Si alguna de las disposiciones aquí contenidas es declarada nula, inválida o inaplicable por una autoridad competente, dicha determinación no afectará la validez de las demás, que permanecerán en pleno vigor. El hecho de que Wonder Mx no ejerza un derecho o no exija el cumplimiento de una obligación en un caso concreto no deberá interpretarse como renuncia a tal derecho u obligación en el futuro.  </li>
                </ol>

            </section>
        </div>
    );
}

function LegalEn() {
    return (
        <div className="legal-container">
            <style dangerouslySetInnerHTML={{
                __html: `
        .legal-container {
          color: #1a1a1a;
          line-height: 1.6;
          font-family: sans-serif;
        }
        .legal-container h1 { font-size: 2.5rem; font-weight: 800; margin-bottom: 2rem; border-bottom: 2px solid #eee; padding-bottom: 1rem; }
        .legal-container h2 { font-size: 1.5rem; font-weight: 700; margin-top: 2.5rem; margin-bottom: 1rem; color: #3048ab; }
        .legal-container h3 { font-size: 1.1rem; font-weight: 700; margin-top: 1.5rem; }
        .legal-container p { margin-bottom: 1.2rem; text-align: justify; }
        .legal-container ul { margin-bottom: 1.2rem; padding-left: 1.5rem; list-style-type: disc; }
        .legal-container li { margin-bottom: 0.5rem; }
      `}} />

            <section>
                <h1 id="t-rminos-y-condiciones">Terms and Conditions</h1>
                <p>These terms govern the relationship between START WORKS MARKETING S.A. DE C.V. “Wonder Mx” and any person who uses the site wondermx.com, consults our services, or books an experience. They are organized as a glossary: each entry defines a term that appears in the relationship between the traveler and Wonder Mx, and within that definition lie the conditions that apply. Use of the site implies acceptance of everything described herein, in accordance with Articles 1792 and 1803 of the Federal Civil Code. </p>
                <ol>
                    <li><strong>Identification.</strong> START WORKS MARKETING S.A. DE C.V., Tax ID (RFC): SWM230217SE3, address: AVENIDA TAMAULIPAS 150, FLOOR 18 INT 1801, COLONIA HIPODROMO, COLONIA HIPODROMO, DELEGACIÓN CUAUHTEMOC, ZIP CODE 06100, MEXICO CITY, email: <a href="mailto:contacto@ournextrip.com.mx" title="mailto:contacto@ournextrip.com.mx">contacto@wondermx.com</a>, site: wondermx.com. For any questions, you may contact us through the site’s form. </li>
                    <li><strong>Experience.</strong> Any tourism service offered by Wonder Mx, whether a catalog activity published on the site or a custom-designed itinerary. This includes, but is not limited to: gastronomic, cultural and adventure tours, transfers, restaurant reservations, wellness activities, VIP-access venues, and combinations of the above. Each catalog experience describes its inclusions, exclusions, and specific conditions on its product page. </li>
                    <li><strong>Custom Quote.</strong> An itinerary proposal prepared by the concierge tailored to the traveler, based on the information provided regarding dates, interests, number of people, and budget. The quote does not create any payment obligation until the traveler expressly approves it. Payment for a custom quote is processed through the Custom Experience section of the site, entering the reference or package name agreed upon with the concierge. </li>
                    <li><strong>Concierge.</strong> The person assigned by Wonder Mx to design, coordinate, and accompany the traveler’s experience. The concierge is the direct point of contact during the trip, available via chat or call to handle changes, questions, or unforeseen situations in real time. Their role is that of an active intermediary between the traveler and providers, not a direct executor of services at the destination. </li>
                    <li><strong>Permitted Use.</strong> The site wondermx.com is available exclusively to individuals with legal capacity to contract who use it for lawful purposes related to consulting and booking tourism experiences. The following is prohibited: using the site for illegal or fraudulent activities; copying, reproducing, or distributing content, images, texts, or design of the site without written authorization from START WORKS MARKETING S.A. DE C.V.; unauthorized use of the Wonder Mx brand, its logo, or any intellectual property element; and introducing malicious code or attempting unauthorized access to systems or databases of the site. </li>
                    <li><strong>Use of the Site.</strong> Access to wondermx.com and submission of the contact form imply acceptance of these terms and Wonder Mx’s Privacy Policy. The site is available to individuals with legal capacity to contract. Wonder Mx reserves the right to reject any request without stating cause. Disputes arising from use of the site or services shall be subject to the jurisdiction of the competent courts of Mexico City, waiving any other jurisdiction. </li>
                    <li><strong>Prices.</strong> All prices published on wondermx.com are shown in national currency, Mexican pesos (MXN), and include Value Added Tax (VAT) unless expressly stated otherwise in a quote or specific product. Prices may vary due to season, availability, and provider policies; however, once the traveler completes payment and receives confirmation, Wonder Mx will honor the agreed price, except in cases of obvious clerical errors (e.g., clearly disproportionate or inconsistent amounts), in which case the traveler will be informed and given the option to proceed at the correct price or cancel with a full refund. </li>
                    <li><strong>Payment Methods.</strong> Wonder Mx accepts payments via credit and debit cards issued by authorized financial institutions, as well as other electronic methods indicated on wondermx.com (e.g., certified payment gateways or other digital payment forms). Availability of payment methods may vary depending on the country of issuance, bank, or gateway conditions. By making payment, the traveler declares they are the holder of the payment method used or have authorization to use it. </li>
                    <li><strong>VAT.</strong> All prices published in the wondermx.com catalog include Value Added Tax at 16%, in accordance with the applicable VAT Law. Prices for custom quotes will include VAT and will be specified in the proposal sent by the concierge. START WORKS MARKETING S.A. DE C.V. will issue the corresponding digital tax receipt for each transaction. </li>
                    <li><strong>Payment.</strong> The site processes payments through an encrypted gateway. Wonder Mx does not store or have access to full bank card details; such handling occurs entirely within the certified processor environment. Payment confirmation activates reservation management. Failure to fulfill an agreed payment in a custom quote voids any reservation commitments made by Wonder Mx with providers. </li>
                    <li><strong>Minimum Advance Notice.</strong> Wonder Mx requests that bookings be made at least 34 calendar days prior to the start date of the experience. This timeframe is necessary to ensure availability with providers. Requests with less notice are handled subject to what can be arranged at that time, and Wonder Mx will clearly indicate what can and cannot be guaranteed within the shorter timeframe. </li>
                    <li><strong>Special Preferences.</strong> Information the traveler may share when contacting or booking: food allergies, accessibility requirements, dietary restrictions, levels of physical activity, or other relevant conditions for designing the experience. Wonder Mx uses this information to make concrete decisions with providers. Accuracy of this information is the traveler’s responsibility; Wonder Mx cannot guarantee accommodations based on incomplete or uncommunicated data. </li>
                    <li><strong>Confirmation.</strong> Upon completing payment for a catalog experience or custom quote, Wonder Mx will send an electronic confirmation to the registered email with transaction details: experience name, date, amount paid, and reservation reference. This confirmation serves as proof of the transaction and is required for any subsequent process. </li>
                    <li><strong>Revocation.</strong> In accordance with Article 56 of the Federal Consumer Protection Law, for purchases made through electronic means, the consumer has the right to revoke consent within five business days following the transaction date, provided the experience has not been executed or started. To exercise this right, the client must notify it in writing to <a href="mailto:contacto@ournextrip.com.mx" title="mailto:contacto@ournextrip.com.mx">contacto@wondermx.com</a> within the stated period. </li>
                    <li><strong>Suspension.</strong> Wonder Mx reserves the right to suspend or cancel access to the site and any ongoing reservation when the following is detected: fraudulent use of the site or payment methods; breach of these terms; use of the service for illegal purposes or that cause harm to third parties; or any conduct Wonder Mx considers incompatible with the nature of the service. In such cases, no refund applies if the breach is attributable to the client. </li>
                    <li><strong>Cancellation.</strong> The act of voiding a confirmed reservation. The financial conditions applicable depending on when the cancellation occurs are fully described in the Wonder Mx Refund Policy, which forms an integral part of these terms. </li>
                    <li><strong>Provider.</strong> An independent third party that directly executes the services composing an experience: restaurants, tour operators, transportation companies, guides, cultural venues, or others. Wonder Mx acts as coordinator and concierge, not as a direct executor. It selects its providers with care but does not control external factors such as third-party operational decisions, capacity, schedules, or destination conditions. In the event of changes by a provider, Wonder Mx will notify the traveler and seek an equivalent alternative. </li>
                    <li><strong>Liability of Wonder Mx.</strong> Wonder Mx acts as designer, coordinator, and concierge of experiences, and in many cases as an intermediary between the traveler and providers who directly execute services at the destination. Responsibility for the material operation of the service (schedules, tour execution, establishment conditions, among others) lies with the provider, in accordance with its own policies. To the extent permitted by applicable law, Wonder Mx shall not be liable for indirect damages, loss of profit, or loss of opportunities arising from the use of the site or contracted services. In the event that direct liability of Wonder Mx toward the traveler is determined, it shall be limited, at most, to the amount actually paid for the specific experience in question, without prejudice to the non-waivable rights granted to consumers under the Federal Consumer Protection Law. </li>
                    <li><strong>Intellectual Property.</strong> The content of the site wondermx.com, including texts, images, design, logos, trade name Wonder Mx, and software, is the property of START WORKS MARKETING S.A. DE C.V. or its licensors and is protected by Mexican intellectual property laws. No element may be reproduced, distributed, or used without express written authorization from START WORKS MARKETING S.A. DE C.V. </li>
                    <li><strong>Force Majeure.</strong> Events beyond the control of Wonder Mx that prevent the execution of an experience: extreme weather conditions, closure of sites by competent authorities, safety situations at the destination, or other unforeseeable and unavoidable events. In such cases, Wonder Mx will first offer rescheduling. If this is not possible or the traveler does not accept it, the refund of the amount paid will be processed minus unrecoverable costs already committed with providers, with a written breakdown. </li>
                    <li><strong>Final Provisions.</strong> These terms and conditions constitute the entire agreement between START WORKS MARKETING S.A. DE C.V. “Wonder Mx” and the traveler regarding the use of wondermx.com and the booking of experiences through the site, replacing any prior understanding or agreement, whether verbal or written, on the same matters. If any provision herein is declared null, invalid, or unenforceable by a competent authority, such determination shall not affect the validity of the remaining provisions, which shall remain in full force. The fact that Wonder Mx does not exercise a right or does not enforce an obligation in a specific case shall not be interpreted as a waiver of such right or obligation in the future. </li>
                </ol>

            </section>
        </div>
    );
}

export default function LegalPage() {
    const locale = useLocale();

    return (
        <div className="min-h-screen flex flex-col bg-white">
            <Header />
            <main className="flex-grow container mx-auto px-6 py-20 max-w-4xl">
                {locale === "es" ? <LegalEs /> : <LegalEn />}
            </main>
            <Footer />
        </div>
    );
}